#ifndef LANG_TYPES_H
#define LANG_TYPES_H 1

typedef enum e_lang_types {
    LANG_CHAR,
    LANG_BYTE,
    LANG_SHORT,
    LANG_INT,
    LANG_LONG,
    LANG_FLOAT,
    LANG_DOUBLE,
    LANG_CONST, // SET CONST FLAG
    LANG_UNSIGNED, // SET UNSIHNED FLAG
    LANG_NULL, // DOES VALUE VARIABLE IS NULL
    LANG_FUNC,
    LANG_STRUCT
} lang_types;

#endif